version: 2.1

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - run: npm install
      - run: npm test

  lint:
    docker:
      - image: node:14
    steps:
      - run: npm run lint

  deploy:
    docker:
      - image: node:14
    steps:
      - run: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - lint
      - deploy:
          requires:
            - build
            - lint
